// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vectra.Avaliacao.Backend.Context;

namespace Vectra.Avaliacao.Backend.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210708144500_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vectra.Avaliacao.Backend.Entities.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Agencia");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cliente");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numero");

                    b.Property<double>("Saldo")
                        .HasColumnType("float")
                        .HasColumnName("Saldo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("Conta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agencia = "9237",
                            Cliente = "Cliente 1",
                            CreatedAt = new DateTime(2021, 7, 8, 11, 45, 0, 423, DateTimeKind.Local).AddTicks(5047),
                            IsActive = true,
                            Numero = "33521-5",
                            Saldo = 0.10000000000000001,
                            UpdatedAt = new DateTime(2021, 7, 8, 11, 45, 0, 423, DateTimeKind.Local).AddTicks(5071)
                        },
                        new
                        {
                            Id = 2,
                            Agencia = "9237",
                            Cliente = "Cliente 2",
                            CreatedAt = new DateTime(2021, 7, 8, 11, 45, 0, 423, DateTimeKind.Local).AddTicks(5117),
                            IsActive = true,
                            Numero = "33521-5",
                            Saldo = 0.10000000000000001,
                            UpdatedAt = new DateTime(2021, 7, 8, 11, 45, 0, 423, DateTimeKind.Local).AddTicks(5119)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
